# Remove these configuration records
# one by one as the offenses are removed from the code base.

# Offense count: 19
Metrics/AbcSize:
  Max: 50

# Offense count: 6
Metrics/CyclomaticComplexity:
  Max: 13

# Offense count: 19
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 35

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 281

# Offense count: 6
Metrics/PerceivedComplexity:
  Max: 16

# Offense count: 1
Style/AccessorMethodName:
  Exclude:
    - 'lib/paper_trail/has_paper_trail.rb'

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: prefer_alias, prefer_alias_method
Style/Alias:
  Exclude:
    - 'lib/paper_trail.rb'
    - 'lib/paper_trail/config.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/version_concern.rb'
    - 'test/dummy/app/models/song.rb'
    - 'test/unit/model_test.rb'

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/unit/ar_id_map_test.rb'

# Offense count: 33
Style/Documentation:
  Enabled: false

# Offense count: 2
Style/ModuleFunction:
  Exclude:
    - 'lib/paper_trail/serializers/json.rb'
    - 'lib/paper_trail/serializers/yaml.rb'

# Offense count: 2
Style/MultilineBlockChain:
  Exclude:
    - 'lib/paper_trail/version_concern.rb'

# Offense count: 4
Style/MultilineTernaryOperator:
  Exclude:
    - 'lib/paper_trail/config.rb'
    - 'lib/paper_trail/has_paper_trail.rb'
    - 'lib/paper_trail/reifier.rb'

# Offense count: 4
# Cop supports --auto-correct.
Style/MutableConstant:
  Exclude:
    - 'lib/generators/paper_trail/templates/create_versions.rb'
    - 'lib/paper_trail/version_number.rb'
    - 'test/dummy/app/models/widget.rb'
    - 'test/unit/associations_test.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/RescueModifier:
  Exclude:
    - 'lib/paper_trail/version_concern.rb'
    - 'spec/models/version_spec.rb'
    - 'test/dummy/app/models/person.rb'
