# frozen_string_literal: true

# This file is automatically generated by `rails generate paper_trail:install`
# and goes in `YourApp/config/initializers/`.
# Each model can override most of these global settings on a per-model basis.

## Enable/disable PaperTrail globally
PaperTrail.config.enabled = true

## Default behaviour tracks versions on all events (create, update, destroy, and touch).
## You may wish to remove touch events to reduce version table size.
PaperTrail.config.has_paper_trail_defaults = {
  on: %i[create update destroy touch]
}

## Limit the number of versions saved per record.
## The version limit does not apply to `create` events
## Default is nil (no limit)
# PaperTrail.config.version_limit = 3

## Define error handling behaviour.
## options:
### :legacy     # Raise on create, log on update/delete (Default)
### :log        # only log the error
### :exception  # raise exception
### :silent     # do nothing
# PaperTrail.config.version_error_behavior = :legacy

## See the readme for other important configuration steps such as setting whodunnit,
## and enabling/disabling paper_trail in tests.
## https://github.com/paper-trail-gem/paper_trail#readme
